/* ══ VERSÃO ════════════════════════════════════════════════════ */
const APP_VERSION = '2.04';
const VERSOES = [
  { v:'1.0',  data:'19/06/2026', autor:'Claude', desc:'Criação do tracker — PCI, cronograma e histórico base' },
  { v:'1.1',  data:'19/06/2026', autor:'Claude', desc:'Adição do sistema de login (admin/visitante) com senha hash SHA-256' },
  { v:'1.2',  data:'19/06/2026', autor:'Claude', desc:'Aba de mão de obra — Barros Rezende · teto R$ 115.000 · projeção e comprovantes' },
  { v:'1.3',  data:'19/06/2026', autor:'Claude', desc:'Aba de materiais — controle de compras por categoria com gráfico de proporção' },
  { v:'1.4',  data:'21/06/2026', autor:'Claude', desc:'Correção: impermeabilização 60% · elétrica 10% · concreto magro ≠ contrapiso · esgoto separado de pluvial' },
  { v:'1.5',  data:'21/06/2026', autor:'Claude', desc:'Itens PCI atualizados com projeto aprovado (3 pavimentos, 227m², 22 portas, 18 janelas)' },
  { v:'1.6',  data:'21/06/2026', autor:'Claude', desc:'Aba de recursos — composição CAIXA/próprios/FGTS · estratégia de desembolso por fase' },
  { v:'1.7',  data:'21/06/2026', autor:'Claude', desc:'Aba de cronograma — 9 medições previstas · conclusão jul/2027 · economia R$ 38.654' },
  { v:'1.8',  data:'21/06/2026', autor:'Claude', desc:'Escala 78% (CAIXA/obra) · % medição = % PCI × 0,7533 · tabela por medição atualizada' },
  { v:'1.9',  data:'21/06/2026', autor:'Claude', desc:'Projeção 2ª medição detalhada item a item · controle de versionamento implementado' },
  { v:'1.10', data:'21/06/2026', autor:'Claude', desc:'Separação confirmado vs estimado — cards, barra e saldo corrigidos' },
  { v:'1.11', data:'21/06/2026', autor:'Claude', desc:'Aba medição com confirmação direta no tracker — botão "Confirmar medição CAIXA" · histórico automático' },
  { v:'1.12', data:'22/06/2026', autor:'Claude', desc:'Previsão alvenaria+pilares corrigida: horizonte de 4 semanas (22/06–18/07/2026), não semana única' },
  { v:'1.13', data:'22/06/2026', autor:'Claude', desc:'Integração aba Materiais completa — MAT_CORES (15 categorias), lista de compras, por categoria, registrar compra' },
  { v:'1.14', data:'22/06/2026', autor:'Claude', desc:'Recursos corrigidos: FGTS zerado (consumido no terreno) · próprios a aportar dez/2026 (13º+PL) · alertas de fluxo de caixa atualizados' },
  { v:'1.15', data:'22/06/2026', autor:'Claude', desc:'Materiais: 24 compras integradas do localStorage (R$ 37.545) — ferragem, cimento, brita, tijolos, piso, esgoto, elétrica e outros' },
  { v:'1.16', data:'22/06/2026', autor:'Claude', desc:'Auto-publish GitHub: ao registrar ou remover material, tracker atualiza o arquivo base automaticamente' },
  { v:'1.17', data:'22/06/2026', autor:'Claude', desc:'Auto-publish expandido para todas as abas: itens PCI, histórico, mão de obra, medições CAIXA e materiais' },
  { v:'1.18', data:'22/06/2026', autor:'Claude', desc:'Cards separados: executado físico vs estimativa CAIXA vs com previsões · % CAIXA por item na tabela de medição · mensagem de avanço mostra delta PCI + CAIXA + valor' },
  { v:'1.19', data:'22/06/2026', autor:'Claude', desc:'Correção itens: impermeabilização locked (medida 1ª med.) · hidráulica zerada · esgoto 1ºpav 100% · estimativa 2ª med. corrigida para ~4,33% CAIXA (~R$16.148)' },
  { v:'1.20', data:'22/06/2026', autor:'Claude', desc:'Cronograma ajustado: 2ª medição corrigida para esgoto completo + magro + elétrica padrão · impermeabilização e hidráulica removidas da fase 2 · datas pilares atualizadas' },
  { v:'1.21', data:'22/06/2026', autor:'Claude', desc:'FGTS removido do cronograma: badges Prop+FGTS → Rec. próprios · fase 5 · explicação e alertas corrigidos' },
  { v:'1.22', data:'22/06/2026', autor:'Claude', desc:'Correção: esgoto 1ºpav removido (sem laje) · 2ª medição corrigida para 3,31% CAIXA ~R$12.340 · histórico limpo · cronograma ajustado' },
  { v:'1.23', data:'22/06/2026', autor:'Claude', desc:'Cards clarificados: "Executado físico (% PCI)" separado de "Estimativa próx. medição (% CAIXA)" · sub mostra relação ×0,7533 explicitamente' },
  { v:'1.24', data:'22/06/2026', autor:'Claude', desc:'Card "Com previsões" removido — informação ambígua · barra e legenda simplificadas' },
  { v:'1.25', data:'22/06/2026', autor:'Claude', desc:'Perfil visitante: sem R$ em nenhum lugar · cards mostram só % · sub do card executado mostra % CAIXA estimado' },
  { v:'1.26', data:'22/06/2026', autor:'Claude', desc:'Visitante: R$ removido do card liberado e legenda · barra de previsão oculta · seção previsões rápidas oculta' },
  { v:'1.27', data:'22/06/2026', autor:'Claude', desc:'Visitante: R$ 30.623 removido do sub do card liberado CAIXA em todas as situações (inicial e ao confirmar medição)' },
  { v:'1.28', data:'22/06/2026', autor:'Claude', desc:'Layout responsivo completo: mobile ≤768px (2 col cards, tabs scroll, tabelas scroll, form 1 col, log compacto) · telas ≤400px (1 col)' },
  { v:'1.29', data:'22/06/2026', autor:'Claude', desc:'Responsivo revisado: barra sem texto embutido no mobile · labels % abaixo da barra · inputs font-size 16px (evita zoom iOS) · cards e tabelas otimizados' },
  { v:'1.30', data:'22/06/2026', autor:'Claude', desc:'Cronograma refeito com prazos Barros Rezende: 7 medições, conclusão mai/2027 (~11 meses), laje separada, chapisco 50 dias, revestimento 20 dias, varanda incluída' },
  { v:'1.31', data:'22/06/2026', autor:'Claude', desc:'Cronograma corrigido: térreo BR (4 medições, conclusão ~30/03/2027) separado de 1º+2º pav (a contratar, datas a definir)' },
  { v:'1.32', data:'22/06/2026', autor:'Claude', desc:'Fontes corrigidas: CAIXA cobre quase toda a obra (R$349.660 de R$372.888) · Rec. próprios só no final da 7ª med. · badges e alertas atualizados' },
  { v:'1.33', data:'22/06/2026', autor:'Claude', desc:'Base CAIXA recalculada: R$354.244 (R$372.888 − R$18.644 bloqueados/habite-se) · todos os valores das 7 medições atualizados · folga ~R$22.067' },
  { v:'1.34', data:'22/06/2026', autor:'Claude', desc:'Recursos corrigidos: FGTS R$11.305 + próprios R$27.000 consumidos no terreno · desconto Campos Urbanismo R$3.159 · próprios para obra R$125.271' },
  { v:'1.35', data:'24/06/2026', autor:'Claude', desc:'Visitante: sem nenhum valor financeiro — ocultos barra de progresso, colunas Liberação/Acum./Saldo do calendário, rodapé da tabela de medições e alert com R$' },
  { v:'1.36', data:'24/06/2026', autor:'Claude', desc:'Itens corrigidos para espelhar exatamente a PCI: item 17 unificado (esgoto+pluviais 4,07%), item 20 corrigido (muro frontal+documentação 7,49%), item 171 removido, concreto magro removido como item separado' },
  { v:'1.37', data:'24/06/2026', autor:'Claude', desc:'Item 17: exec corrigido de 66% para 23% — esgoto térreo = ~1/3 do total de 3 pavimentos, pluviais zerados' },
  { v:'1.38', data:'24/06/2026', autor:'Claude', desc:'Item 20: exec corrigido para 0% — docs iniciais já capturados no item 1, muro frontal não iniciado, docs finais (habite-se/CND/averbação) pendentes' },
  { v:'1.39', data:'24/06/2026', autor:'Claude', desc:'Item 4: exec 11% (6 fiadas térreo 23–28/06) · Item 13: exec 12% (concreto magro térreo 80,14m²) · estimativa próx. med. ~R$15.549' },
  { v:'1.40', data:'28/06/2026', autor:'Claude', desc:'Item 4: exec 15% — 8 fiadas em todas as paredes do térreo até 27/06 · estimativa medição sexta ~R$16.418' },
  { v:'1.41', data:'06/07/2026', autor:'Claude', desc:'Itens PCI atualizados conforme PLS 2ª med (03/07/2026): Supra 35%, Alvenaria 40%, Impermeab 60%, Elétrica 30%, Hidráulica 20%, Esgoto 100% · estimativa ~R$ 63.904' },
  { v:'1.42', data:'06/07/2026', autor:'Claude', desc:'Estimativa 2ª medição corrigida: ~R$63.718 (17,12% PLS × R$372.888) — PLS já entrega % em escala CAIXA' },
  { v:'1.43', data:'06/07/2026', autor:'Claude', desc:'2ª medição registrada: 25,35% acumulado PLS · R$63.718 · MEDICOES_DEF e histórico atualizados' },
  { v:'1.44', data:'09/07/2026', autor:'Claude', desc:'2ª medição CONSOLIDADA — pagamento CAIXA efetuado: R$63.718 (17,12%) · acum. R$94.341 · itens PLS travados (locked) · acumulados 3ª–7ª recalculados sobre R$372.888' },
  { v:'1.45', data:'09/07/2026', autor:'Claude', desc:'Valor real da 2ª medição: R$63.701,54 depositado pela CAIXA · acumulado R$94.324,54' },
  { v:'1.46', data:'09/07/2026', autor:'Claude', desc:'Item 3 (supraestrutura): físico corrigido para 0% — PLS lançou 35% antecipado (pago), mas nada executado. Divergência físico×PLS registrada no item' },
  { v:'1.47', data:'09/07/2026', autor:'Claude', desc:'Supraestrutura restaurada para 35% conforme PLS — a PLS assinada pelo RT é a fonte oficial de avanço da obra' },
  { v:'1.48', data:'20/07/2026', autor:'Claude', desc:'Novo bloco na aba Recursos: desembolso consolidado material + mão de obra, % do PCI, comparativo com liberado CAIXA, saldo em caixa e desvio físico×financeiro' },
  { v:'1.49', data:'20/07/2026', autor:'Claude', desc:'Madeira/fôrma R$1.500 realocada: removida da aba Mão de obra (duplicidade) e mantida apenas em Materiais · desembolso passa a somar lançamentos tipo material de ambas as abas' },
  { v:'1.50', data:'20/07/2026', autor:'Claude', desc:'Base do desembolso corrigida: percentuais passam a ser calculados sobre o saldo p/ obra R$372.888 (financiamento R$454.488 − R$81.600 do terreno) em vez do PCI R$495.000' },
  { v:'1.51', data:'23/07/2026', autor:'Claude', desc:'Tema claro/escuro com botão no login e no header (preferência salva no navegador) · nova opção de login: usuário externo cria o próprio controle de custos, com orçamento e teto de MO próprios, dados só no navegador dele e publicação no GitHub bloqueada' },
  { v:'2.00', data:'24/07/2026', autor:'Claude', desc:'Dados migrados para a nuvem (Supabase): login por e-mail e senha, cadastro aberto, várias obras por conta com código único (tag) e abas para alternar, gravação no banco em vez do navegador, acesso público removido e token do GitHub retirado do código' },
  { v:'2.01', data:'24/07/2026', autor:'Claude', desc:'Tela de login ganha a opção Consultar obra: com o código (OBR-XXXXXX) qualquer pessoa vê o avanço físico das etapas, sem login e sem nenhum dado financeiro' },
  { v:'2.02', data:'24/07/2026', autor:'Claude', desc:'Recuperação de senha: link Esqueci a senha na tela de login envia e-mail (Supabase) com link seguro; ao voltar, abre tela para definir nova senha' },
  { v:'2.03', data:'11/08/2026', autor:'Claude', desc:'Correção da fórmula de conversão CAIXA: fator ×0,7533 removido — validado com valores reais das medições 1 (R$30.622,88 / 8,23% PCI) e 2 (R$63.701,54 / 17,12% PCI na etapa), confirmando que % CAIXA = % PCI executado, aplicado direto sobre a base R$372.888' },
  { v:'2.04', data:'24/09/2026', autor:'Claude', desc:'Gravação na nuvem em transação única com aviso de conflito entre abas/editores · textos escapados (proteção contra HTML injetado) · remoção do login antigo, modo externo e publicação no GitHub · orçamento e teto de MO vindos da obra aberta · cronograma, contrato e orçamento de MO por item exibidos só na obra original' },
];

/* ══ CONFIG ══════════════════════════════════════════════════ */
let   STORAGE_KEY = 'tracker_obra';   // redefinida por obra em abrirObra()
let BASE_OBRA   = 0;
let ORCAMENTO   = 0;   // custo total (PCI) da obra aberta
let MED_PCT     = 0;   // % e valor já liberados pela CAIXA (soma das medições confirmadas)
let MED_VAL     = 0;
